# Generated by Django 5.1.3 on 2025-02-03 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("is_major_company", models.BooleanField(default=False)),
                ("establishment_date", models.CharField(max_length=7)),
                (
                    "investment_scale",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "job_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("career_year", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "profile",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("lank", models.CharField(blank=True, max_length=10, null=True)),
                ("language_description", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="profile_manager.profile",
                    ),
                ),
            ],
            options={
                "db_table": "language",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="profile_manager.profile",
                    ),
                ),
            ],
            options={
                "db_table": "certificate",
            },
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "career_start_date",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "career_end_date",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "is_currently_employed",
                    models.BooleanField(default=False, null=True),
                ),
                ("career_description", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="careers",
                        to="profile_manager.company",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="careers",
                        to="profile_manager.profile",
                    ),
                ),
            ],
            options={
                "db_table": "career",
                "ordering": ["-career_start_date"],
            },
        ),
        migrations.CreateModel(
            name="AcademicRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("major", models.CharField(blank=True, max_length=100, null=True)),
                ("degree", models.IntegerField(blank=True, null=True)),
                (
                    "enrollment_date",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "graduation_date",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_records",
                        to="profile_manager.profile",
                    ),
                ),
            ],
            options={
                "db_table": "academic_record",
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.CreateModel(
            name="ProfileData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_data",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "processed_data",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("pdf_data", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_data",
                        to="profile_manager.profile",
                    ),
                ),
            ],
            options={
                "db_table": "profile_data",
            },
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tech_stack_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_stacks",
                        to="profile_manager.profile",
                    ),
                ),
            ],
            options={
                "db_table": "tech_stack",
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_analysis", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarked_by",
                        to="profile_manager.profile",
                    ),
                ),
            ],
            options={
                "db_table": "bookmark",
                "unique_together": {("user", "profile")},
            },
        ),
    ]
