# Generated by Django 5.1.3 on 2024-12-27 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "job_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("career_year", models.IntegerField(blank=True, null=True)),
                ("original_data", models.TextField(blank=True, null=True)),
                ("processed_data", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="profile_manager.profile",
                    ),
                ),
            ],
            options={
                "db_table": "language",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="profile_manager.profile",
                    ),
                ),
            ],
            options={
                "db_table": "certificate",
            },
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("responsibilities", models.TextField(blank=True, null=True)),
                ("start_date", models.CharField(blank=True, max_length=7, null=True)),
                ("end_date", models.CharField(blank=True, max_length=7, null=True)),
                ("is_currently_employed", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="careers",
                        to="profile_manager.profile",
                    ),
                ),
            ],
            options={
                "db_table": "career",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="AcademicRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("major", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True, default="graduated", max_length=20, null=True
                    ),
                ),
                (
                    "enrollment_date",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "graduation_date",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_records",
                        to="profile_manager.profile",
                    ),
                ),
            ],
            options={
                "db_table": "academic_record",
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tech_stack_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_stacks",
                        to="profile_manager.profile",
                    ),
                ),
            ],
            options={
                "db_table": "tech_stack",
            },
        ),
    ]
