# Generated by Django 5.1.3 on 2024-12-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="is_currently_employed",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
