# Generated by Django 5.1.3 on 2024-12-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="profile",
            table="profile",
        ),
    ]
