# Generated by Django 5.1.3 on 2025-01-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="establishment_date",
            field=models.CharField(max_length=7),
        ),
    ]
