# Generated by Django 5.1.3 on 2024-12-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiledata",
            name="original_data",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="profiledata",
            name="pdf_data",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="profiledata",
            name="processed_data",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
