# Generated by Django 5.1.3 on 2025-02-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiledata",
            name="ai_analysis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
