# Generated by Django 5.1.3 on 2025-01-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0002_alter_career_is_currently_employed"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="ai_analysis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
