# Generated by Django 5.1.3 on 2025-01-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0002_alter_company_establishment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="company_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
