# Generated by Django 5.1.3 on 2024-12-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0002_alter_profiledata_original_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicrecord",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
