# Generated by Django 5.1.3 on 2024-12-19 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0002_educationcontent_education_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="activity_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="activity_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="organization_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="career",
            name="employment_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="career",
            name="responsibilities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="job",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile_detail",
            name="brief_introduction",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="LLM_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_data", models.TextField(blank=True, null=True)),
                ("processed_data", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_data",
                        to="profile_manager.profile_detail",
                    ),
                ),
            ],
            options={
                "db_table": "llm_data",
            },
        ),
        migrations.CreateModel(
            name="ParticipatedProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "project_role",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "organization_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participated_projects",
                        to="profile_manager.profile_detail",
                    ),
                ),
            ],
            options={
                "db_table": "participated_project",
            },
        ),
    ]
