# Generated by Django 5.1.3 on 2025-01-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0004_career_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
